export type City = {
  nameRu: string;
  nameAz: string;
  districtsRu: string[];
  districtsAz: string[];
};

export const cities: City[] = [
  { nameRu: "26 школа", nameAz: "26 məktəb", districtsRu: ["26 школа"], districtsAz: ["26 məktəb"] },
  { nameRu: "Баку", nameAz: "Bakı", districtsRu: ["Бинагади", "Нариманов", "Насими", "Низами", "Сабаиль", "Сураханы", "Хатаи", "Ясамал", "Гарадаг", "Пираллахы", "Сабунчи"], districtsAz: ["Binəqədi", "Nərimanov", "Nəsimi", "Nizami", "Səbail", "Suraxanı", "Xətai", "Yasamal", "Qaradağ", "Pirallahı", "Sabunçu"] },
  { nameRu: "Сумгаит", nameAz: "Sumqayıt", districtsRu: ["Меркез", "Хырдалан"], districtsAz: ["Mərkəz", "Xırdalan"] },
  { nameRu: "Гянджа", nameAz: "Gəncə", districtsRu: ["Кяпяз", "Низами"], districtsAz: ["Kəpəz", "Nizami"] },
  { nameRu: "Хырдалан", nameAz: "Xırdalan", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Мингячевир", nameAz: "Mingəçevir", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Ширван", nameAz: "Şirvan", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Ленкорань", nameAz: "Lənkəran", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Шеки", nameAz: "Şəki", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Евлах", nameAz: "Yevlax", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Нафталан", nameAz: "Naftalan", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Губа", nameAz: "Quba", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Гусар", nameAz: "Qusar", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Хачмаз", nameAz: "Xaçmaz", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Шамкир", nameAz: "Şəmkir", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Товуз", nameAz: "Tovuz", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Газах", nameAz: "Qazax", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Гёйчай", nameAz: "Göyçay", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Зардаб", nameAz: "Zərdab", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Барда", nameAz: "Bərdə", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Агджабеди", nameAz: "Ağcabədi", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Агдаш", nameAz: "Ağdaş", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Агсу", nameAz: "Ağsu", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Сабирабад", nameAz: "Sabirabad", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Сальян", nameAz: "Salyan", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Нефтчала", nameAz: "Neftçala", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Имишли", nameAz: "İmişli", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Бейлаган", nameAz: "Beyləqan", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Физули", nameAz: "Füzuli", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Джебраил", nameAz: "Cəbrayıl", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Зангилан", nameAz: "Zəngilan", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Лачин", nameAz: "Laçın", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Кельбаджар", nameAz: "Kəlbəcər", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Шуша", nameAz: "Şuşa", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Ходжалы", nameAz: "Xocalı", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Ходжавенд", nameAz: "Xocavənd", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Агдам", nameAz: "Ağdam", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Тертер", nameAz: "Tərtər", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Геранбой", nameAz: "Goranboy", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Дашкесан", nameAz: "Daşkəsən", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Гёйгёль", nameAz: "Göygöl", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Исмаиллы", nameAz: "İsmayıllı", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Шабран", nameAz: "Şabran", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Сиязань", nameAz: "Siyəzən", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Огуз", nameAz: "Oğuz", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Загатала", nameAz: "Zaqatala", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Гах", nameAz: "Qax", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Балакен", nameAz: "Balakən", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Астара", nameAz: "Astara", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Масаллы", nameAz: "Masallı", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Джалильабад", nameAz: "Cəlilabad", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Ярдымлы", nameAz: "Yardımlı", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Лерик", nameAz: "Lerik", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Билясувар", nameAz: "Biləsuvar", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Уджар", nameAz: "Ucar", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Кюрдамир", nameAz: "Kürdəmir", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Самух", nameAz: "Samux", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
  { nameRu: "Абшерон", nameAz: "Abşeron", districtsRu: ["Меркез"], districtsAz: ["Mərkəz"] },
];

export const citiesListRu = cities.map((c) => c.nameRu);
export const citiesListAz = cities.map((c) => c.nameAz);
